package sbjs

/*
// Example generated by sblock. CAN BE DELETED.

const Koa = require('koa')
const mount = require('koa-mount')
const {
	sblock,
} = require('sblock4koa')

const app = new Koa()

app.use(mount(
	'/public',
	sblock(
		require("sblock4js"),
		require("./raw")
	)
))
app.listen(3000)

*/
