package sbjs

/*
// Example generated by sblock. CAN BE DELETED.

const NewFs = require("sblock4js")
const Raw = require("./raw")

const http = require('http')
const Koa = require('koa')
const mount = require('koa-mount')

const {
	serve,
} = require('sblock4koa')

const [vfs, err] = NewFs(Raw)
if (err != null) {
	throw err
}

const app = new Koa()

app.use(mount('/public', serve(vfs)))
http.createServer(app.callback()).listen(3000)

*/
